server/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :blocks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "blocks#index"

  resources :blocks, only: [:index]
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

server/app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  # before_action :set_block, only: %i[ show edit update destroy ]

  # GET /blocks or /blocks.json
  def index
    result = GetLatestBlocksCommand.call(count: 10)
    @blocks = result.blocks

    respond_to do |format|
      format.html
      format.json { render json: @blocks }
    end
  end

  # GET /blocks/1 or /blocks/1.json
  # def show
  # end

  # # GET /blocks/new
  # def new
  #   @block = Block.new
  # end

  # # GET /blocks/1/edit
  # def edit
  # end

  # # POST /blocks or /blocks.json
  # def create
  #   @block = Block.new(block_params)

  #   respond_to do |format|
  #     if @block.save
  #       format.html { redirect_to block_url(@block), notice: "Block was successfully created." }
  #       format.json { render :show, status: :created, location: @block }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @block.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /blocks/1 or /blocks/1.json
  # def update
  #   respond_to do |format|
  #     if @block.update(block_params)
  #       format.html { redirect_to block_url(@block), notice: "Block was successfully updated." }
  #       format.json { render :show, status: :ok, location: @block }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @block.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /blocks/1 or /blocks/1.json
  # def destroy
  #   @block.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to blocks_url, notice: "Block was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_block
  #     @block = Block.find(params[:id])
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def block_params
  #     params.fetch(:block, {})
  #   end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/blocks_helper.rb
module BlocksHelper
end

server/app/views/blocks/_block.html.erb
<div id="<%= dom_id block %>">
</div>

server/app/views/blocks/_form.html.erb
<%= form_with(model: block) do |form| %>
  <% if block.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
        <% block.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

server/app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render "form", block: @block %>

<br>

<div>
  <%= link_to "Show this block", @block %> |
  <%= link_to "Back to blocks", blocks_path %>
</div>

server/app/views/blocks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blocks</h1>

<table id="blocks">
  <thead>
    <tr>
      <th>Height</th>
      <th>Time</th>
      <th>Transactions</th>
      <th>Size</th>
    </tr>
  </thead>
  <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block['height'] %></td>
        <td><%= block['time'] %></td>
        <td><%= block['nTx'] %></td>
        <td><%= block['size'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

server/app/views/blocks/new.html.erb
<h1>New block</h1>

<%= render "form", block: @block %>

<br>

<div>
  <%= link_to "Back to blocks", blocks_path %>
</div>

server/app/views/blocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @block %>

<div>
  <%= link_to "Edit this block", edit_block_path(@block) %> |
  <%= link_to "Back to blocks", blocks_path %>

  <%= button_to "Destroy this block", @block, method: :delete %>
</div>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockExplorer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>